permut : permut.o file.o
	gcc -g -Wall -ansi -pedantic permut.o file.o -o premut

premut.o : premut.c premut.h
	gcc -c -Wall -ansi -pedantic permut.c -o permut.o
	
file.o : file.c file.h
	gcc -c -Wall -ansi -pedantic file.c -o file.o